version: '3.1'

services:
  v2ray-server:
    image: v2fly/v2fly-core
    container_name: v2ray-server
    restart: always
    network_mode: "host"
    volumes:
      - ./server.json:/etc/v2ray/server.json

  v2ray-client:
    image: v2fly/v2fly-core
    container_name: v2ray-client
    restart: always
    network_mode: "host"
    volumes:
      - ./client.json:/etc/v2ray/client.json