version: '3.1'

services:
  gost:
    image: ginuerzh/gost
    container_name: gost
    restart: always
    ports:
      - 8080:8080
    command: [ "-L", ":8080", "-F" ,"http://admin:123456@192.168.1.1:8081" ]