version: '3.1'

services:
  gost:
    image: gogost/gost
    container_name: gost
    restart: always
    ports:
      - 18080:8080
    command: -L :8080 -F 127.0.0.1:40000

  gost-https:
    image: gogost/gost
    container_name: gost-https
    restart: always
    volumes:
      - /etc/letsencrypt/live/{domain}/fullchain.pem:/bin/cert.pem
      - /etc/letsencrypt/live/{domain}/privkey.pem:/bin/key.pem
    network_mode: host
    command: -L http2://{username}:{password}@{domain}:443?probeResistance=code:403 -F 127.0.0.1:40000