version: '3.1'

services:
  ngx:
    image: nginx:latest
    container_name: ngx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs:/etc/nginx/logs
      - ./static:/home/static
    restart: always